# aws s3 bucket configuration
cloud:
  aws:
    credentials:
      access-key: accessKey
      secret-key: secretKey
    region:
      static: aws-region
    stack:
      auto: false
# bucket names
application:
  bucket:
    optimized:
      name: optimizedImageBucketName
    original:
      name: originalImageBucketName

spring:
  profiles:
    active: dev
  # log DB configuration
  datasource:
    url: jdbc:h2:mem:logDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 7575

original:
  height: 100
  width: 100
  quality: 10
  scaleType: CROP
  fillColor: 121221
  type: JPG

thumbNail:
  height: 50
  width: 50
  quality: 7
  scaleType: SKEW
  fillColor: 21312
  type: PNG

source:
  root-url: https://www.debijenkorf.nl/INTERSHOP/static/WFS/dbk-shop-Site/-/dbk-shop/nl_NL/product-images/
